### ISSUE TITLE
Wrong credit in README

### ISSUE THREAD

**Issue by atifaziz** [elmahio/Elmah-Schema#1]
> ELMAH configuration XML Schema file originally created by @atifaziz

I never created this. [Credit goes to `JeffLingis`](https://github.com/elmah/Elmah/issues/239#issuecomment-134663186) [and `davidadarman`](https://github.com/elmah/Elmah/issues/239#issuecomment-134663192).

**Comment by ThomasArdal** [comment]
Fixed :+1:
