### ISSUE TITLE
Support thirdparty errorlog implementations

### ISSUE THREAD

**Issue by ThomasArdal** [elmahio/Elmah-Schema#2]
The current schema supports configuration of the errorlog implementations delivered with ELMAH only. It would be nice to have a schema that would support third party implementations as well (like contribs, elmah.io etc.).

**Comment by ThomasArdal** [comment]
What's your thoughts on this @atifaziz? Update the current Elmah.xsd or create a new one including all of the contribs?

**Comment by atifaziz** [comment]
I'm in a position to make an informed decision but since you asked, I don't see the harm in updating the current for sake of convenience. After all, it's a superficial XSD for the purpose of providing IntelliSense in VS only.

**Comment by ThomasArdal** [comment]
Closing this one for now. Support is added for elmah.io. If contrib projects wants support added to the schema, please add a new issue.
