### ISSUE TITLE
Remove security, errorMail, errorLog and errorFilter from root?

### ISSUE THREAD

**Issue by ThomasArdal** [elmahio/Elmah-Schema#3]
@atifaziz You may remember, that I moved the XML scheme you did, from this issue: https://github.com/elmah/Elmah/issues/239. I've stumbled upon something that may be an issue.

In the schema, we find the following:

```xml
<xs:element name="elmah">
  <xs:complexType>
    <xs:all>
      <xs:element name="security" type="securityCT" minOccurs="0" maxOccurs="1" />
      <xs:element name="errorMail" type="errorMailCT" minOccurs="0" maxOccurs="1" />
      <xs:element name="errorLog" type="errorLogCT" minOccurs="0" maxOccurs="1" />
      <xs:element name="errorFilter" type="errorFilterCT" minOccurs="0" maxOccurs="1" />
    </xs:all>
  </xs:complexType>
</xs:element>
<xs:element name="security" type="securityCT" />
<xs:element name="errorMail" type="errorMailCT" />
<xs:element name="errorLog" type="errorLogCT" />
<xs:element name="errorFilter" type="errorFilterCT" />
<xs:complexType name="securityCT">
  <xs:attribute name="allowRemoteAccess" use="optional" type="xs:boolean" />
</xs:complexType>
...
```

The first part tells us that we can have the following construct:

```xml
<configuration>
  <elmah>
      <security ... />
      <errorMail ... />
      <errorLog ... />
      <errorFilter ... />
  </elmah>
</configuration>
```
But having these repeated in the root:

```xml
<xs:element name="security" type="securityCT" />
<xs:element name="errorMail" type="errorMailCT" />
<xs:element name="errorLog" type="errorLogCT" />
<xs:element name="errorFilter" type="errorFilterCT" />
```

would allow for this:

```xml
<configuration>
    <security ... />
    <errorMail ... />
    <errorLog ... />
    <errorFilter ... />
</configuration>
```

Do you remember if there is a reason for repeating the four elements. In my head, they only make sense within an `<elmah>` element 😄

**Comment by atifaziz** [comment]
I never wrote that schema definition. It was contributed by "JeffLingis". When issues were migrated from Google Code, they were reported as having been authored by me; it's misleading. In the footer of each comment (and where applicable), you'll see the original reporter, like in the footer of the [opening comment](https://github.com/elmah/Elmah/issues/239#issue-103066692) for elmah/Elmah#239:

> ---
> Originally reported on Google Code with ID 239
>
> Reported by `JeffLingis` on 2011-07-13 14:28:14

**Comment by ThomasArdal** [comment]
I'm getting old. This is the second time I miscredited you (https://github.com/elmahio/Elmah-Schema/issues/1) 😆 Thanks!

**Comment by ThomasArdal** [comment]
I cannot seem to track down Jeff. I think I'll just make the change. The current state doesn't look right.
